service: morning-cd

provider:
  name: aws
  runtime: python3.6

package:
  include:
    - morning_cd/**

functions:
  spotify-access-token:
    description: Fetch spotify access token
    handler:
      morning_cd/delivery/aws_lambda/spotify_access_token.handler
    events:
      - http:
          path: /api/accesstoken
          method: get
    environment:
      SPOTIFY_CLIENT_ID: 87734dfae0b7432488270b2fc1ff2e30
      SPOTIFY_CLIENT_SECRET: 42ad3ab71bd648fa9725879fc4ec61e2

custom:
  client:
    bucketName: morning.cd
    distributionFolder: web_client/build
    errorDocument: index.html

plugins:
  - serverless-python-requirements
  - serverless-finch
