service: morning-cd

provider:
  name: aws
  runtime: python3.7

custom:
  client:
    bucketName: morningcd.com
    distributionFolder: web_client/build
    errorDocument: index.html

plugins:
  - serverless-finch
