version: 2

commands:
  installPythonDependencies:
    description: "Install python dependencies from Pipfile.lock and cache results."

    steps:
      - restore_cache:
          keys:
            - pipenv-cache-{{ checksum "Pipfile.lock" }}
            - pipenv-cache-

      - run:
          name: Install dependencies
          command: pipenv sync --dev

      - save_cache:
          key: pipenv-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

  installJsDependencies:
    steps:
      - restore_cache:
          keys:
            - js-cache-{{ checksum "web_client/yarn.lock" }}
            - js-cache-

      - run:
          name: Install dependencies
          working_directory: web_client
          command: yarn install

      - save_cache:
          key: js-cache-{{ checksum "web_client/yarn.lock" }}
          paths: node_modules


jobs:
  test-python:
    docker:
      - image: circleci/python:3.6.7-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - installPythonDependencies

      - run:
          name: Run mypy
          command: pipenv run mypy morning_cd/

      - run:
          name: Run flake8
          command: pipenv run flake8 morning_cd/

      - run:
          name: Run pytest
          command: pipenv run pytest --junitxml=test-results/pytest/results.xml

      - store_test_results:
          path: test-results

  test-js:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - installJsDependencies

      - run:
          name: Run tests
          working_directory: web_client
          environment:
            JEST_JUNIT_OUTPUT: "../test-results/jest/results.xml"
          command: yarn test:ci

      - store_test_results:
          path: test-results

workflows:
  version: 2

  build:
    jobs:
      - test-python
      - test-js
