version: 2.1

########
# JOBS #
########
jobs:
  test-client:
    executor: js-executor
    steps:
      - checkout
      - install-js-dependencies
      - run:
          name: Run tests
          working_directory: web_client
          environment:
            JEST_JUNIT_OUTPUT: "../test-results/jest/results.xml"
          command: yarn test:ci
      - store_test_results:
          path: test-results

  build-client:
    executor: js-executor
    steps:
      - checkout
      - install-js-dependencies
      - run:
          name: Build js client
          working_directory: web_client
          command: yarn build
      - persist_to_workspace:
          root: web_client
          paths:
            - build

  deploy:
    executor: js-executor
    steps:
      - checkout
      - install-sls-dependencies
      - attach_workspace:
          at: web_client
      - run:
          name: Deploy client to s3 bucket
          command: yarn run sls client deploy --no-confirm

#############
# WORKFLOWS #
#############
workflows:
  version: 2
  build:
    jobs:
      - test-client
      - build-client

      # master jobs
      - deploy-hold:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - test-client
            - build-client

      - deploy:
          filters:
            branches:
              only: master
          requires:
            - deploy-hold

#############
# EXECUTORS #
#############
executors:
  js-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

############
# COMMANDS #
############
commands:
  install-js-dependencies:
    steps:
      - restore_cache:
          keys:
            - js-cache-{{ checksum "web_client/yarn.lock" }}
            - js-cache-
      - run:
          name: Install dependencies
          working_directory: web_client
          command: yarn install
      - save_cache:
          key: js-cache-{{ checksum "web_client/yarn.lock" }}
          paths: web_client/node_modules

  install-sls-dependencies:
    steps:
      - restore_cache:
          keys:
            - sls-cache-{{ checksum "yarn.lock" }}
            - sls-cache-
      - run:
          name: Install serverless dependencies
          command: yarn install
      - save_cache:
          key: sls-cache-{{ checksum "yarn.lock" }}
          paths: node_modules
